name: Alchemy Soccer Collective
favicon: null
layout_spectrum: 0.9540529276710004
typography_spectrum: 0.5598224250134081
title: Alchemy Soccer Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000216'
    - '#745e51'
    - '#e2c2a1'
    - '#004240'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
